import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'id' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: 'en',
      setLanguage: (lang) => set({ language: lang }),
    }),
    {
      name: 'ontime-language-storage',
    }
  )
);

export const translations = {
  id: {
      common: {
      newBadge: 'Badge Baru!',
      deadlineWarning: 'Peringatan Tenggat!',
      deadlineApproaching: 'Deadline Mendekat!',
      hoursLeft: (hours: number) => `${hours} jam lagi`,
      expiringSoon: (title: string) => `${title} akan segera berakhir`,
      systemOnline: 'SISTEM ONLINE',
      commandCenter: 'WATCHLIST',
      missionTimeline: 'LINIMASA MISI',
      studyManager: 'MANAJER STUDI',
      taskBoard: 'PAPAN TUGAS',
      trainingArena: 'ARENA BELAJAR',
      guildHall: 'GUILD HALL',
      profile: 'PROFIL PEMAIN',
      playerLevel: 'LEVEL PEMAIN',
      xp: 'XP',
      season: 'MUSIM',
      back: 'Kembali',
      advance: 'Lanjut',
      delete: 'Hapus',
      close: 'Tutup',
    },
    layout: {
      navigation: 'NAVIGASI',
    },
    dashboard: {
      title: 'WATCHLIST',
      subtitle: 'Pantau status tugas, level kekuatan, dan aktivitas progres Anda.',
      weeklyPower: 'Kekuatan Mingguan',
      hours: 'Jam',
      urgentTask: 'TUGAS MENDESAK',
      urgentTaskSubtitle: (count: number) => `Anda memiliki ${count} task yang mendekati deadline dalam 48 jam!`,
      playerStats: 'Statistik Pemain',
      tasksDone: 'Tugas Selesai',
      trainingTime: 'Waktu Latihan',
      skillTrees: 'Skill Trees',
      focusSessions: 'Sesi Fokus',
      dailyBriefing: 'Briefing Tugas Harian',
      activityRadar: 'Radar Aktivitas',
      recentTraining: 'Latihan Terbaru',
      noRecentTraining: 'Belum ada sesi training.',
      downloadReport: 'Unduh Laporan Battle',
      generateStudyPlan: 'BUAT RENCANA BELAJAR',
      studyPlanGenerated: 'Study plan berhasil dibuat untuk hari ini!',
      todayStudyPlan: 'RENCANA BELAJAR HARI INI',
      missionsPending: 'Misi Tersisa',
      noStudyPlan: 'Belum ada rencana belajar hari ini',
      generatePrompt: 'Buat rencana dari Watchlist untuk memulai training',
      analyzing: 'Analisis jadwal minggu ini',
      prioritizing: 'Membuat prioritas',
      developing: 'Menyusun jadwal',
      generatingPlan: 'Menyusun Rencana...',
      authenticating: 'Otentikasi Google',
      fetchingData: 'Mengumpulkan data jadwal',
      uploading: 'Menyinkronisasi ke Cloud',
      syncing: 'Menyinkronkan...',
      tip: 'Tip: Belajar 25 menit fokus + 5 menit istirahat terbukti efektif untuk materi kompleks.',
      lastMonth: 'Bulan Lalu',
      now: 'Sekarang',
      recommendationUrgent: (title: string) => `Task Urgent: "${title}" mendekati deadline! Alokasikan 2 jam hari ini untuk menyelesaikannya.`,
      recommendationReview: (topic: string) => `Skill Check: Materi "${topic}" perlu training ulang. Jadwalkan review session minggu ini.`,
      recommendationClear: "All clear, Commander! Semua task terkendali. Gunakan waktu luang untuk grinding materi minggu depan.",
    },
    tasks: {
      title: 'PAPAN TUGAS',
      subtitle: 'Kelola tugas akademik Anda. Tarik & lepas untuk memperbarui status tugas.',
      newTask: 'Tugas Baru',
      newTasksCol: 'DRAFT TUGAS',
      inProgressCol: 'DALAM PROSES',
      completedCol: 'SELESAI',
      legendary: 'LEGENDARIS',
      rare: 'LANGKA',
      common: 'UMUM',
      taskComplete: 'TUGAS SELESAI',
      subTasks: 'Sub-tugas',
      addTaskTitle: 'Tugas Baru',
      taskLabel: 'Judul Tugas',
      taskPlaceholder: 'Misal: Laporan Praktikum Jarkom',
      typeLabel: 'Tipe Tugas',
      rarityLabel: 'Rarity (Prioritas)',
      deadlineLabel: 'Tenggat Waktu',
      rewardLabel: 'Bobot Hadiah (%)',
      acceptBtn: 'Terima Tugas',
      bounties: 'MISI',
      archive: 'ARSIP',
      postBounty: 'POST MISI',
      allTasks: 'SEMUA MISI',
      criticalPriority: 'PRIORITAS KRITIS',
      noBounties: 'BELUM ADA MISI',
      archiveEmpty: 'ARSIP KOSONG',
      cleared: 'SELESAI',
      strategySuggestion: 'SARAN STRATEGI',
      completeTask: 'SELESAIKAN MISI',
      taskAccomplished: 'MISI TUNTAS',
    },
    study: {
      title: 'STUDY ARENA',
      subtitle: 'Level up skill Anda. Mulai training session dan pantau skill tree progress.',
      manageSkillTrees: 'Kelola Skill Trees',
      trainingInProgress: 'LATIHAN SEDANG BERLANGSUNG',
      endTraining: 'Akhiri Latihan',
      selectSkillTree: '-- Pilih Skill Tree --',
      skillTreeLabel: 'Skill Tree',
      trainingTopicLabel: 'Training Topic',
      trainingTopicPlaceholder: 'Misal: Latihan Kalkulus Integral',
      beginTraining: 'Mulai Sesi Belajar',
      viewSkillTree: 'LIHAT SKILL TREE',
      runSession: 'JALANKAN SESI BELAJAR',
      manualSession: 'Sesi Manual',
      startStudySession: 'Mulai Sesi Belajar',
      start: 'MULAI',
      selectTopic: 'Pilih Topik',
      newTopic: 'Topik Baru...',
      timer: 'TIMER',
      skillTreesTitle: 'Skill Trees',
      trainingLogTitle: 'Training Log',
      noTrainingRecorded: 'Belum ada sesi training.\nMulai sesi pertamamu!',
      powerLevel: 'PWR',
      trainingComplete: 'Training Selesai!',
      ratePowerLevel: 'Beri rating power level untuk materi ini:',
      weak: 'Lemah',
      mastered: 'Dikuasai',
      editSkillTree: 'Edit Skill Tree',
      newSkillTree: 'Skill Tree Baru',
      skillTreeName: 'Nama Skill Tree',
      targetHours: 'Target Jam (Season)',
      skillNodes: 'Skill Nodes',
      addSkillNodePlaceholder: 'Tambah node skill baru...',
      saveChanges: 'Simpan Perubahan',
      addSkillTree: 'Tambah Skill Tree',
      skillTreePlaceholder: 'Misal: Kecerdasan Buatan',
    },
    academic: {
      title: 'STUDY MANAGER',
      subtitle: 'Kelola mata kuliah, jadwal, dan progres akademik Anda.',
      addCourse: 'Tambah Mata Kuliah',
      editCourse: 'Edit Mata Kuliah',
      courseName: 'Nama Mata Kuliah',
      courseCode: 'Kode Mata Kuliah',
      sks: 'Bobot SKS',
      type: 'Tipe Kuliah',
      schedule: 'Jadwal',
      day: 'Hari',
      startTime: 'Jam Mulai',
      endTime: 'Jam Selesai',
      room: 'Ruangan',
      lecturer: 'Dosen',
      wajib: 'Wajib',
      pilihan: 'Pilihan',
      mengulang: 'Mengulang',
      generalInfo: 'Info Umum',
      addSlot: 'Tambah Slot',
      confirmUpdate: 'Konfirmasi Perubahan',
      acceptArchives: 'Terima Arsip',
      noCourses: 'Belum ada mata kuliah yang ditambahkan.',
      days: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'],
    },
    profile: {
      title: 'PROFIL PEMAIN',
      subtitle: 'Kelola data semester dan pantau statistik performa Anda.',
      semester: 'Semester',
      addSemester: 'Tambah Semester',
      editSemester: 'Edit Semester',
      deleteSemester: 'Hapus Semester Ini',
      semesterNumber: 'No. Semester',
      academicYear: 'Tahun Ajar',
      semesterType: 'Tipe Semester',
      ganjil: 'Ganjil',
      genap: 'Genap',
      totalSks: 'Jumlah SKS',
      noSemester: 'Belum ada data semester. Tekan tombol di bawah untuk menambahkan.',
      statsTitle: 'Base Stats',
      radarTitle: 'Skill Radar',
      playerLevel: 'Player Level',
      viewActivityLog: 'Lihat Activity Log Lengkap',
      activityMonitor: 'Monitor Aktivitas',
      noRecords: 'Tidak ada rekaman tersedia',
      expPoints: 'EXP POINTS',
      totalAccumulation: 'Total Akumulasi',
      activityLogTitle: 'Activity Log Lengkap',
      activityLogSubtitle: 'Rekaman riwayat perolehan XP Player',
    },
    chat: {
      title: 'GUILD HALL',
      subtitle: 'Chat P2P dengan party members. Privasi total, pesan tidak disimpan di server manapun.',
      onlineStatus: 'Online',
      connectedMembers: (count: number) => `${count} Party Members Terhubung`,
      exportKey: 'Export',
      exit: 'Keluar',
      participantsTitle: 'Anggota Party',
      myProfile: 'Profil Saya',
      guildMaster: 'Guild Master',
      partyMember: 'Anggota Party',
      startConversation: 'Mulai percakapan guild Anda!',
      replyingTo: (name: string) => `Membalas ${name}`,
      inputPlaceholder: 'Tulis pesan...',
      itemTradeTitle: 'Item Trade',
      instantMode: 'Mode Instan',
      instantModeDesc: 'Langsung kirim ke semua orang.',
      waitingMode: 'Mode Tunggu (On-Waiting)',
      waitingModeDesc: 'Kirim hanya saat ada yang meminta.',
      cancel: 'Batal',
      share: 'Bagikan',
      inviteTitle: 'Undang Anggota Party',
      inviteDesc: 'Bagikan tautan atau QR code ini untuk mengajak teman ke guild Anda.',
      copyLink: 'Salin Link Undangan',
      close: 'Tutup',
      displayNameLabel: 'Nama Tampilan',
      displayNamePlaceholder: 'Masukkan nama pemain Anda...',
      joinGuildBtn: 'Gabung Guild',
      createGuildBtn: 'Buat Guild Baru',
      joinViaFile: 'Gabung via Keyroom',
      scanQrBtn: 'Scan QR Guild',
      connectingTitle: 'Menghubungkan ke Guild...',
      connectingDesc: 'Menjalin peer connection. Stand by, adventurer.',
      or: 'atau',
      scanError: 'Gagal mengakses kamera. Pastikan izin diberikan.',
      invalidQr: 'QR Code tidak valid.',
      unknownQr: 'Format QR Code tidak dikenal.',
      noQrFound: 'Tidak dapat menemukan QR Code di gambar ini.',
      guildChamber: 'Guild Chamber',
      startCamera: 'Mulai Kamera',
      chooseQrImage: 'Pilih Gambar QR',
      scanInstruction: 'Arahkan kamera ke QR Code atau unggah gambar yang berisi QR Code ruangan.',
    },
    stats: {
      title: 'STATISTIK',
      subtitle: 'Analisis performa belajar dan produktivitas Anda.',
      thisWeekStudy: 'Belajar Minggu Ini',
      tasksCompleted: 'Task Selesai',
      mostProductiveDay: 'Hari Paling Produktif',
      currentStreak: 'Streak Saat Ini',
      progressChart: 'Grafik Progres',
      personalRecommendations: 'Rekomendasi Personal',
      weeklyComparison: 'Perbandingan Mingguan',
      taskBreakdown: 'Rincian Task',
    },
    achievements: {
      trophyCase: 'Trophy Case',
      locked: 'Terkunci',
      newBadge: 'Badge Baru!',
      unlocked: 'Terbuka',
      total: 'Total Achievements',
    },
    notifications: {
      title: 'Notifikasi',
      deadlineApproaching: 'Deadline Mendekat!',
      streakActive: 'Streak Aktif!',
      markAllRead: 'Tandai Semua Dibaca',
      clearAll: 'Hapus Semua',
      noNotifications: 'Tidak ada notifikasi',
    },
  },
  en: {
    common: {
      newBadge: 'New Badge!',
      deadlineWarning: 'Deadline Warning!',
      deadlineApproaching: 'Deadline Approaching!',
      hoursLeft: (hours: number) => `${hours} hours left`,
      expiringSoon: (title: string) => `${title} is expiring soon`,
      systemOnline: 'SYSTEM ONLINE',
      commandCenter: 'WATCHLIST',
      missionTimeline: 'MISSION TIMELINE',
      studyManager: 'STUDY MANAGER',
      taskBoard: 'TASK BOARD',
      trainingArena: 'STUDY ARENA',
      guildHall: 'GUILD HALL',
      profile: 'PLAYER PROFILE',
      playerLevel: 'PLAYER LEVEL',
      xp: 'XP',
      season: 'SEASON',
      back: 'Back',
      advance: 'Advance',
      delete: 'Delete',
      close: 'Close',
    },
    layout: {
      navigation: 'NAVIGATION',
    },
    dashboard: {
      title: 'WATCHLIST',
      subtitle: 'Monitor task status, power level, and your progression activity.',
      weeklyPower: 'Weekly Power',
      hours: 'Hours',
      urgentTask: 'URGENT TASK',
      urgentTaskSubtitle: (count: number) => `You have ${count} tasks approaching deadline within 48 hours!`,
      playerStats: 'Player Stats',
      tasksDone: 'Tasks Done',
      trainingTime: 'Training Time',
      skillTrees: 'Skill Trees',
      focusSessions: 'Focus Sessions',
      dailyBriefing: 'Daily Task Briefing',
      activityRadar: 'Activity Radar',
      recentTraining: 'Recently Trained',
      noRecentTraining: 'No training sessions yet.',
      downloadReport: 'Download Battle Report',
      generateStudyPlan: 'GENERATE STUDY PLAN',
      studyPlanGenerated: 'Study plan successfully generated for today!',
      todayStudyPlan: 'TODAY\'S STUDY PLAN',
      missionsPending: 'Missions Pending',
      noStudyPlan: 'No study plan generated today',
      generatePrompt: 'Generate a plan from the Watchlist to start training',
      analyzing: 'Analyzing weekly schedule',
      prioritizing: 'Creating priority mapping',
      developing: 'Developing schedule',
      generatingPlan: 'Generating Plan...',
      authenticating: 'Authenticating Google Session',
      fetchingData: 'Fetching schedules and events',
      uploading: 'Uploading to Google Cloud',
      syncing: 'Syncing...',
      tip: 'Tip: 25 mins focus + 5 mins break is proven effective for complex materials.',
      lastMonth: 'Last Month',
      now: 'Now',
      recommendationUrgent: (title: string) => `Urgent Task: "${title}" is approaching deadline! Allocate 2 hours today to complete it.`,
      recommendationReview: (topic: string) => `Skill Check: Topic "${topic}" needs retraining. Schedule a review session this week.`,
      recommendationClear: "All clear, Commander! All tasks under control. Use free time for grinding next week's material.",
    },
    tasks: {
      title: 'TASK BOARD',
      subtitle: 'Manage your academic tasks. Drag & drop to update task status.',
      newTask: 'New Task',
      newTasksCol: 'NEW TASKS',
      inProgressCol: 'IN PROGRESS',
      completedCol: 'COMPLETED',
      legendary: 'LEGENDARY',
      rare: 'RARE',
      common: 'COMMON',
      taskComplete: 'TASK COMPLETE',
      subTasks: 'Sub-tasks',
      addTaskTitle: 'New Task',
      taskLabel: 'Task Title',
      taskPlaceholder: 'e.g. Database Lab Report',
      typeLabel: 'Task Type',
      rarityLabel: 'Rarity (Priority)',
      deadlineLabel: 'Deadline',
      rewardLabel: 'Reward Weight (%)',
      acceptBtn: 'Accept Task',
      bounties: 'MISSIONS',
      archive: 'ARCHIVE',
      postBounty: 'POST MISSION',
      allTasks: 'ALL MISSIONS',
      criticalPriority: 'CRITICAL PRIORITY',
      noBounties: 'NO ACTIVE MISSIONS',
      archiveEmpty: 'ARCHIVE IS EMPTY',
      cleared: 'CLEARED',
      strategySuggestion: 'STRATEGY SUGGESTION',
      completeTask: 'COMPLETE MISSION',
      taskAccomplished: 'MISSION ACCOMPLISHED',
    },
    study: {
      title: 'STUDY ARENA',
      subtitle: 'Level up your skills. Start training sessions and monitor skill tree progress.',
      manageSkillTrees: 'Manage Skill Trees',
      trainingInProgress: 'TRAINING IN PROGRESS',
      endTraining: 'End Training',
      selectSkillTree: '-- Select Skill Tree --',
      skillTreeLabel: 'Skill Tree',
      trainingTopicLabel: 'Training Topic',
      trainingTopicPlaceholder: 'e.g., Integral Calculus Practice',
      beginTraining: 'Begin Training',
      viewSkillTree: 'VIEW SKILL TREE',
      runSession: 'RUN STUDY SESSION',
      manualSession: 'Manual Session',
      startStudySession: 'Start Study Session',
      start: 'START',
      selectTopic: 'Select Topic',
      newTopic: 'New Topic...',
      timer: 'TIMER',
      skillTreesTitle: 'Skill Trees',
      trainingLogTitle: 'Training Log',
      noTrainingRecorded: 'No training recorded yet.\nBegin your first session!',
      powerLevel: 'PWR',
      trainingComplete: 'Training Complete!',
      ratePowerLevel: 'Rate your power level for this material:',
      weak: 'Weak',
      mastered: 'Mastered',
      editSkillTree: 'Edit Skill Tree',
      newSkillTree: 'New Skill Tree',
      skillTreeName: 'Skill Tree Name',
      targetHours: 'Target Hours (Season)',
      skillNodes: 'Skill Nodes',
      addSkillNodePlaceholder: 'Add new skill node...',
      saveChanges: 'Save Changes',
      addSkillTree: 'Add Skill Tree',
      skillTreePlaceholder: 'e.g. Artificial Intelligence',
    },
    academic: {
      title: 'STUDY MANAGER',
      subtitle: 'Manage your courses, schedules, and academic progress.',
      addCourse: 'Add Course',
      editCourse: 'Edit Course',
      courseName: 'Course Name',
      courseCode: 'Course Code',
      sks: 'SKS Weight',
      type: 'Course Type',
      schedule: 'Schedule',
      day: 'Day',
      startTime: 'Start Time',
      endTime: 'End Time',
      room: 'Room',
      lecturer: 'Lecturer',
      wajib: 'Required',
      pilihan: 'Elective',
      mengulang: 'Retake',
      generalInfo: 'General Info',
      addSlot: 'Add Slot',
      confirmUpdate: 'Confirm Update',
      acceptArchives: 'Accept Archives',
      noCourses: 'No courses added yet.',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    profile: {
      title: 'PLAYER PROFILE',
      subtitle: 'Manage your semesters and monitor your performance stats.',
      semester: 'Semester',
      addSemester: 'Add Semester',
      editSemester: 'Edit Semester',
      deleteSemester: 'Delete This Semester',
      semesterNumber: 'Semester No.',
      academicYear: 'Academic Year',
      semesterType: 'Semester Type',
      ganjil: 'Odd',
      genap: 'Even',
      totalSks: 'Total SKS',
      noSemester: 'No semester data found. Click the button below to add one.',
      statsTitle: 'Base Stats',
      radarTitle: 'Skill Radar',
      playerLevel: 'Player Level',
      viewActivityLog: 'View Full Activity Log',
      activityMonitor: 'Activity Monitor',
      noRecords: 'No records available',
      expPoints: 'EXP POINTS',
      totalAccumulation: 'Total Accumulation',
      activityLogTitle: 'Full Activity Log',
      activityLogSubtitle: 'Player XP gain history record',
    },
    chat: {
      title: 'GUILD HALL',
      subtitle: 'P2P chat with party members. Total privacy, messages are not stored on any server.',
      onlineStatus: 'Online',
      connectedMembers: (count: number) => `${count} Party Members Connected`,
      exportKey: 'Export',
      exit: 'Exit',
      participantsTitle: 'Party Members',
      myProfile: 'My Profile',
      guildMaster: 'Guild Master',
      partyMember: 'Party Member',
      startConversation: 'Start your guild conversation!',
      replyingTo: (name: string) => `Replying to ${name}`,
      inputPlaceholder: 'Write a message...',
      itemTradeTitle: 'Item Trade',
      instantMode: 'Instant Mode',
      instantModeDesc: 'Send directly to everyone.',
      waitingMode: 'Waiting Mode (On-Waiting)',
      waitingModeDesc: 'Send only when requested.',
      cancel: 'Cancel',
      share: 'Share',
      inviteTitle: 'Invite Party Members',
      inviteDesc: 'Share this link or QR code to invite friends to your guild.',
      copyLink: 'Copy Invite Link',
      close: 'Close',
      displayNameLabel: 'Display Name',
      displayNamePlaceholder: 'Enter your player name...',
      joinGuildBtn: 'Join Guild',
      createGuildBtn: 'Create New Guild',
      joinViaFile: 'Join via Keyroom',
      scanQrBtn: 'Scan QR Guild',
      connectingTitle: 'Connecting to Guild...',
      connectingDesc: 'Establishing peer connection. Stand by, adventurer.',
      or: 'or',
      scanError: 'Failed to access camera. Make sure permissions are granted.',
      invalidQr: 'Invalid QR Code.',
      unknownQr: 'Unknown QR Code format.',
      noQrFound: 'No QR Code found in this image.',
      guildChamber: 'Guild Chamber',
      startCamera: 'Start Camera',
      chooseQrImage: 'Choose QR Image',
      scanInstruction: 'Point your camera at the QR Code or upload an image containing the room QR Code.',
    },
    stats: {
      title: 'STATISTICS',
      subtitle: 'Analyze your study performance and productivity.',
      thisWeekStudy: 'Study This Week',
      tasksCompleted: 'Tasks Completed',
      mostProductiveDay: 'Most Productive Day',
      currentStreak: 'Current Streak',
      progressChart: 'Progress Chart',
      personalRecommendations: 'Personal Recommendations',
      weeklyComparison: 'Weekly Comparison',
      taskBreakdown: 'Task Breakdown',
    },
    achievements: {
      trophyCase: 'Trophy Case',
      locked: 'Locked',
      newBadge: 'New Badge!',
      unlocked: 'Unlocked',
      total: 'Total Achievements',
    },
    notifications: {
      title: 'Notifications',
      deadlineApproaching: 'Deadline Approaching!',
      streakActive: 'Streak Active!',
      markAllRead: 'Mark All Read',
      clearAll: 'Clear All',
      noNotifications: 'No notifications',
    },
  }
};
